#!/usr/bin/env python3
"""
Script to record (s,t) coordinates generated by the dSPACE simulator.

This script:
1. Generates random (x,y,z) world coordinates on the Laguna Seca track
2. Validates positions against the road network to ensure they're on drivable areas
3. Runs Scenic to convert them to (s,t) coordinates via the dSPACE simulator
4. Records the mapping from world coords -> (s,t) for calibration purposes

Usage:
    python record_st_coordinates_v2.py --num-samples 10
"""

import argparse
import csv
import random
import sys
import os
from pathlib import Path

# Add Scenic to path if needed
scenic_path = Path(__file__).parent.parent.parent / "src"
if scenic_path.exists():
    sys.path.insert(0, str(scenic_path))

# Import after path is set
from scenic.formats.opendrive import xodr_parser
from scenic.simulators.dspace import utils as dutils


def validate_position_on_road(x, y, road_network, tolerance=5.0):
    """Check if a position is on a drivable road.
    
    Args:
        x, y: World coordinates
        road_network: Scenic road network object
        tolerance: Distance tolerance in meters
        
    Returns:
        bool: True if position is on drivable road
    """
    try:
        from scenic.core.vectors import Vector
        from scenic.core.geometry import Point
        
        # Create a point at the given coordinates
        point = Point(x, y)
        
        # Check if the point is within the drivable region
        if hasattr(road_network, 'drivableRegion'):
            drivable_region = road_network.drivableRegion
            if drivable_region.contains(point.buffer(tolerance)):
                return True
        
        # Alternative: check against individual roads
        if hasattr(road_network, 'roads'):
            for road in road_network.roads:
                if hasattr(road, 'drivableRegion'):
                    if road.drivableRegion.contains(point.buffer(tolerance)):
                        return True
        
        return False
        
    except Exception as e:
        print(f"Warning: Could not validate position ({x:.2f}, {y:.2f}): {e}")
        return False


def sample_points_on_track(xodr_path, num_samples=10, step=2.0, max_attempts=100):
    """Sample random points along the track centerline with validation.
    
    Returns:
        List of (x, y, z, s_raw) tuples
    """
    print(f"Loading track from: {xodr_path}")
    
    # Build reference line
    refline, total_length = dutils.build_circuit_refline(xodr_path, step=step)
    print(f"Track length: {total_length:.1f}m with {len(refline)} reference points")
    
    # Load road network for validation
    print("Loading road network for validation...")
    try:
        road_map = xodr_parser.RoadMap()
        road_map.parse(str(xodr_path))
        road_map.calculate_geometry(num=100, calc_gap=False, calc_intersect=False)
        print("Road network loaded successfully")
    except Exception as e:
        print(f"Warning: Could not load road network for validation: {e}")
        road_map = None
    
    samples = []
    attempts = 0
    
    # Sample uniformly along the track with validation
    while len(samples) < num_samples and attempts < max_attempts:
        attempts += 1
        
        # Pick a random s-coordinate
        s_target = random.uniform(0, total_length)
        
        # Find the corresponding (x, y, z) using linear interpolation
        x, y, z = dutils.st_to_world(refline, s_target, t=0.0)
        
        # Validate position if we have a road network
        if road_map is not None:
            # Check if position is on drivable road
            is_valid = False
            
            # Check against drivable region
            try:
                from shapely.geometry import Point
                point = Point(x, y)
                
                # Check if point is within drivable region
                if hasattr(road_map, 'drivable_region') and road_map.drivable_region:
                    if road_map.drivable_region.contains(point.buffer(5.0)):
                        is_valid = True
                
                # If not in drivable region, check individual roads
                if not is_valid and hasattr(road_map, 'roads'):
                    for road in road_map.roads.values():
                        if hasattr(road, 'drivable_region') and road.drivable_region:
                            if road.drivable_region.contains(point.buffer(5.0)):
                                is_valid = True
                                break
                                
            except Exception as e:
                print(f"Warning: Validation error for ({x:.2f}, {y:.2f}): {e}")
                is_valid = True  # Assume valid if validation fails
        
        else:
            # No road network available, assume valid
            is_valid = True
        
        if is_valid:
            # Store the sample
            samples.append({
                'x': x,
                'y': y,
                'z': z,
                's_raw': s_target,
                's_aurelion': None,  # Will be filled in by simulator
                't_aurelion': None,  # Will be filled in by simulator
            })
            
            print(f"Sample {len(samples)}: s={s_target:.1f}m -> ({x:.2f}, {y:.2f}, {z:.2f}) ✓")
        else:
            print(f"Attempt {attempts}: s={s_target:.1f}m -> ({x:.2f}, {y:.2f}, {z:.2f}) ✗ (not on road)")
    
    if len(samples) < num_samples:
        print(f"Warning: Only found {len(samples)} valid positions out of {num_samples} requested")
        print(f"Consider increasing --max-attempts or checking the road network")
    
    return samples, refline, total_length


def generate_scenic_file(samples, output_path):
    """Generate a Scenic file with cars at the sampled positions."""
    
    lines = [
        "# --- Map and timing (must come before the model line) ---",
        "param map = localPath('../../assets/maps/dSPACE/LagunaSeca.xodr')",
        "param time_step = 1.0/10",
        "",
        "# --- Driving world model (brings in Car/road/behaviors) ---",
        "model scenic.domains.driving.model",
        "",
        "# --- Fellow cars placed at sampled coordinates ---",
    ]
    
    for i, sample in enumerate(samples, 1):
        x, y, z = sample['x'], sample['y'], sample['z']
        lines.append(f"# Location {i}: ({x:.6f}, {y:.6f}, {z:.6f}) s_raw={sample['s_raw']:.2f}")
        lines.append(f"fellow{i} = new Car at ({x:.6f}, {y:.6f}, {z:.6f})")
        lines.append("")
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"\nGenerated Scenic file: {output_path}")
    return output_path


def parse_simulator_output(output_text):
    """Parse the s,t coordinates from simulator output.
    
    Looks for lines like:
    "Transformed world coordinates (X, Y) to road coordinates (s=S, t=T)"
    """
    st_coords = []
    
    for line in output_text.split('\n'):
        if 'Transformed world coordinates' in line and 'to road coordinates' in line:
            # Extract s and t values
            # Format: "... (s=VALUE, t=VALUE)"
            try:
                parts = line.split('(s=')[1].split(',')
                s_val = float(parts[0].strip())
                t_val = float(parts[1].split('t=')[1].split(')')[0].strip())
                st_coords.append((s_val, t_val))
            except Exception as e:
                print(f"Warning: Could not parse line: {line}")
                print(f"  Error: {e}")
    
    return st_coords


def record_results(samples, st_coords, output_csv):
    """Record the mapping from world coords to (s,t) coords."""
    
    if len(st_coords) != len(samples):
        print(f"Warning: Expected {len(samples)} s,t pairs but got {len(st_coords)}")
    
    # Update samples with s,t coordinates
    for i, (s, t) in enumerate(st_coords):
        if i < len(samples):
            samples[i]['s_aurelion'] = s
            samples[i]['t_aurelion'] = t
    
    # Write to CSV
    with open(output_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=[
            'x', 'y', 'z', 's_raw', 's_aurelion', 't_aurelion'
        ])
        writer.writeheader()
        writer.writerows(samples)
    
    print(f"\nRecorded results to: {output_csv}")
    
    # Print summary
    print("\n=== Summary ===")
    print(f"{'x':<12} {'y':<12} {'z':<8} {'s_raw':<10} {'s_aurelion':<12} {'t_aurelion':<12}")
    print("-" * 80)
    for sample in samples:
        print(f"{sample['x']:<12.2f} {sample['y']:<12.2f} {sample['z']:<8.2f} "
              f"{sample['s_raw']:<10.2f} {sample.get('s_aurelion', 'N/A')!s:<12} "
              f"{sample.get('t_aurelion', 'N/A')!s:<12}")


def main():
    parser = argparse.ArgumentParser(description='Record (s,t) coordinates from dSPACE simulator')
    parser.add_argument('--num-samples', type=int, default=10,
                        help='Number of sample points to generate (default: 10)')
    parser.add_argument('--xodr', type=str,
                        default='../../assets/maps/dSPACE/LagunaSeca.xodr',
                        help='Path to XODR file')
    parser.add_argument('--output-scenic', type=str,
                        default='fellow_placing_sampled_v2.scenic',
                        help='Output Scenic file path')
    parser.add_argument('--output-csv', type=str,
                        default='st_coordinates_v2.csv',
                        help='Output CSV file for recorded coordinates')
    parser.add_argument('--step', type=float, default=2.0,
                        help='Sampling step size for track reference line (default: 2.0m)')
    parser.add_argument('--max-attempts', type=int, default=100,
                        help='Maximum attempts to find valid positions (default: 100)')
    
    args = parser.parse_args()
    
    # Resolve paths
    script_dir = Path(__file__).parent
    xodr_path = script_dir / args.xodr
    output_scenic = script_dir / args.output_scenic
    output_csv = script_dir / args.output_csv
    
    if not xodr_path.exists():
        print(f"Error: XODR file not found: {xodr_path}")
        return 1
    
    # Step 1: Sample points on track
    print("=" * 80)
    print("Step 1: Sampling points on track with validation")
    print("=" * 80)
    samples, refline, total_length = sample_points_on_track(
        xodr_path, args.num_samples, args.step, args.max_attempts
    )
    
    # Step 2: Generate Scenic file
    print("\n" + "=" * 80)
    print("Step 2: Generating Scenic file")
    print("=" * 80)
    scenic_file = generate_scenic_file(samples, output_scenic)
    
    # Step 3: Instruct user to run Scenic
    print("\n" + "=" * 80)
    print("Step 3: Run Scenic with dSPACE simulator")
    print("=" * 80)
    print("\nTo generate the ModelDesk file and record (s,t) coordinates, run:")
    print(f"\n  scenic {output_scenic} --2d --model scenic.simulators.dspace.model --simulate > output.log 2>&1")
    print("\nThen run this script again with --parse-output option:")
    print(f"\n  python {Path(__file__).name} --parse-output output.log --input-csv {output_csv}")
    
    # Step 4: Save preliminary results
    record_results(samples, [], output_csv)
    
    print("\n" + "=" * 80)
    print("Done! Generated files:")
    print(f"  - Scenic file: {output_scenic}")
    print(f"  - CSV file (preliminary): {output_csv}")
    print("=" * 80)
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
