#!/usr/bin/env python3
"""
Script to record (s,t) coordinates generated by the dSPACE simulator.

This script:
1. Generates random (x,y,z) world coordinates on the Laguna Seca track
2. Runs Scenic to convert them to (s,t) coordinates via the dSPACE simulator
3. Records the mapping from world coords -> (s,t) for calibration purposes

Usage:
    python record_st_coordinates.py --num-samples 10
"""

import argparse
import csv
import random
import sys
import os
from pathlib import Path

# Add Scenic to path if needed
scenic_path = Path(__file__).parent.parent.parent / "src"
if scenic_path.exists():
    sys.path.insert(0, str(scenic_path))

# Import after path is set
from scenic.formats.opendrive import xodr_parser
from scenic.simulators.dspace import utils as dutils


def sample_points_on_track(xodr_path, num_samples=10, step=2.0):
    """Sample random points along the track centerline.
    
    Returns:
        List of (x, y, z, s_raw) tuples
    """
    print(f"Loading track from: {xodr_path}")
    
    # Build reference line
    refline, total_length = dutils.build_circuit_refline(xodr_path, step=step)
    print(f"Track length: {total_length:.1f}m with {len(refline)} reference points")
    
    samples = []
    
    # Sample uniformly along the track
    for i in range(num_samples):
        # Pick a random s-coordinate
        s_target = random.uniform(0, total_length)
        
        # Find the corresponding (x, y, z) using linear interpolation
        x, y, z = dutils.st_to_world(refline, s_target, t=0.0)
        
        # Store the sample
        samples.append({
            'x': x,
            'y': y,
            'z': z,
            's_raw': s_target,
            's_aurelion': None,  # Will be filled in by simulator
            't_aurelion': None,  # Will be filled in by simulator
        })
        
        print(f"Sample {i+1}: s={s_target:.1f}m -> ({x:.2f}, {y:.2f}, {z:.2f})")
    
    return samples, refline, total_length


def generate_scenic_file(samples, output_path):
    """Generate a Scenic file with cars at the sampled positions."""
    
    lines = [
        "# --- Map and timing (must come before the model line) ---",
        "param map = localPath('../../assets/maps/dSPACE/LagunaSeca.xodr')",
        "param time_step = 1.0/10",
        "",
        "# --- Driving world model (brings in Car/road/behaviors) ---",
        "model scenic.domains.driving.model",
        "",
        "# --- Fellow cars placed at sampled coordinates ---",
    ]
    
    for i, sample in enumerate(samples, 1):
        x, y, z = sample['x'], sample['y'], sample['z']
        lines.append(f"# Location {i}: ({x:.6f}, {y:.6f}, {z:.6f}) s_raw={sample['s_raw']:.2f}")
        lines.append(f"fellow{i} = new Car at ({x:.6f}, {y:.6f}, {z:.6f})")
        lines.append("")
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"\nGenerated Scenic file: {output_path}")
    return output_path


def parse_simulator_output(output_text):
    """Parse the s,t coordinates from simulator output.
    
    Looks for lines like:
    "Transformed world coordinates (X, Y) to road coordinates (s=S, t=T)"
    """
    st_coords = []
    
    for line in output_text.split('\n'):
        if 'Transformed world coordinates' in line and 'to road coordinates' in line:
            # Extract s and t values
            # Format: "... (s=VALUE, t=VALUE)"
            try:
                parts = line.split('(s=')[1].split(',')
                s_val = float(parts[0].strip())
                t_val = float(parts[1].split('t=')[1].split(')')[0].strip())
                st_coords.append((s_val, t_val))
            except Exception as e:
                print(f"Warning: Could not parse line: {line}")
                print(f"  Error: {e}")
    
    return st_coords


def record_results(samples, st_coords, output_csv):
    """Record the mapping from world coords to (s,t) coords."""
    
    if len(st_coords) != len(samples):
        print(f"Warning: Expected {len(samples)} s,t pairs but got {len(st_coords)}")
    
    # Update samples with s,t coordinates
    for i, (s, t) in enumerate(st_coords):
        if i < len(samples):
            samples[i]['s_aurelion'] = s
            samples[i]['t_aurelion'] = t
    
    # Write to CSV
    with open(output_csv, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=[
            'x', 'y', 'z', 's_raw', 's_aurelion', 't_aurelion'
        ])
        writer.writeheader()
        writer.writerows(samples)
    
    print(f"\nRecorded results to: {output_csv}")
    
    # Print summary
    print("\n=== Summary ===")
    print(f"{'x':<12} {'y':<12} {'z':<8} {'s_raw':<10} {'s_aurelion':<12} {'t_aurelion':<12}")
    print("-" * 80)
    for sample in samples:
        print(f"{sample['x']:<12.2f} {sample['y']:<12.2f} {sample['z']:<8.2f} "
              f"{sample['s_raw']:<10.2f} {sample.get('s_aurelion', 'N/A')!s:<12} "
              f"{sample.get('t_aurelion', 'N/A')!s:<12}")


def main():
    parser = argparse.ArgumentParser(description='Record (s,t) coordinates from dSPACE simulator')
    parser.add_argument('--num-samples', type=int, default=10,
                        help='Number of sample points to generate (default: 10)')
    parser.add_argument('--xodr', type=str,
                        default='../../assets/maps/dSPACE/LagunaSeca.xodr',
                        help='Path to XODR file')
    parser.add_argument('--output-scenic', type=str,
                        default='fellow_placing_sampled.scenic',
                        help='Output Scenic file path')
    parser.add_argument('--output-csv', type=str,
                        default='st_coordinates.csv',
                        help='Output CSV file for recorded coordinates')
    parser.add_argument('--step', type=float, default=2.0,
                        help='Sampling step size for track reference line (default: 2.0m)')
    
    args = parser.parse_args()
    
    # Resolve paths
    script_dir = Path(__file__).parent
    xodr_path = script_dir / args.xodr
    output_scenic = script_dir / args.output_scenic
    output_csv = script_dir / args.output_csv
    
    if not xodr_path.exists():
        print(f"Error: XODR file not found: {xodr_path}")
        return 1
    
    # Step 1: Sample points on track
    print("=" * 80)
    print("Step 1: Sampling points on track")
    print("=" * 80)
    samples, refline, total_length = sample_points_on_track(xodr_path, args.num_samples, args.step)
    
    # Step 2: Generate Scenic file
    print("\n" + "=" * 80)
    print("Step 2: Generating Scenic file")
    print("=" * 80)
    scenic_file = generate_scenic_file(samples, output_scenic)
    
    # Step 3: Instruct user to run Scenic
    print("\n" + "=" * 80)
    print("Step 3: Run Scenic with dSPACE simulator")
    print("=" * 80)
    print("\nTo generate the ModelDesk file and record (s,t) coordinates, run:")
    print(f"\n  scenic {output_scenic} --2d --model scenic.simulators.dspace.model --simulate > output.log 2>&1")
    print("\nThen run this script again with --parse-output option:")
    print(f"\n  python {Path(__file__).name} --parse-output output.log --input-csv {output_csv}")
    
    # Step 4: Save preliminary results
    record_results(samples, [], output_csv)
    
    print("\n" + "=" * 80)
    print("Done! Generated files:")
    print(f"  - Scenic file: {output_scenic}")
    print(f"  - CSV file (preliminary): {output_csv}")
    print("=" * 80)
    
    return 0


if __name__ == '__main__':
    sys.exit(main())

